FROM bitnami/spark:3.4.1


USER root
RUN pip install pandas pyarrow requests sqlalchemy psycopg2-binary python-dateutil


USER root
COPY spark/ /opt/spark-apps/
COPY scripts/ /opt/spark-apps/scripts/
ENV DATA_RAW_DIR=/opt/data/raw
ENV DATA_PROCESSED_DIR=/opt/data/processed
RUN mkdir -p $DATA_RAW_DIR $DATA_PROCESSED_DIR
